# version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cheapbob-postgres
    environment:
      POSTGRES_USER: cheap
      POSTGRES_PASSWORD: bob
      POSTGRES_DB: cheapbob
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - cheapbob-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cheap -d cheapbob"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cheapbob-redis
    networks:
      - cheapbob-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7-jammy
    container_name: cheapbob-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: cheap
      MONGO_INITDB_ROOT_PASSWORD: bob
      MONGO_INITDB_DATABASE: cheapbob
    volumes:
      - mongodb-data:/data/db
    networks:
      - cheapbob-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../../backend
      dockerfile: ../docker/back-prd/Dockerfile
    container_name: cheapbob-backend
    env_file:
      - ../../backend/.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - cheapbob-network

networks:
  cheapbob-network:
    driver: bridge

volumes:
  postgresql-data:
    name: cheapbob-prd-postgresql-data
  redis-data:
    name: cheapbob-prd-redis-data
  mongodb-data:
    name: cheapbob-prd-mongodb-data