# FROM node:20-alpine as build

# WORKDIR /frontend
# RUN corepack enable && corepack prepare pnpm@latest --activate

# COPY package.json pnpm-lock.yaml ./
# RUN pnpm install --frozen-lockfile

# COPY . .
# RUN pnpm build