# # version: '3.8'

# services:
#   frontend-build:
#     build:
#       context: ../../frontend
#       dockerfile: ../docker/front-prd/Dockerfile
#     container_name: frontend-builder
#     volumes:
#       - ../../frontend/dist:/frontend/dist
#       - /var/www/cheap-bob/dist:/mnt/dist-host
#     command: >
#       sh -c "pnpm install &&
#       pnpm build &&
#       rm -rf /mnt/dist-host/* &&
#       cp -r dist/* /mnt/dist-host/"