"""소비자 상세 정보 테이블 추가

Revision ID: 09d0c4536d4a
Revises: 8a8f1111ff14
Create Date: 2025-09-11 06:44:43.389846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d0c4536d4a'
down_revision: Union[str, Sequence[str], None] = '8a8f1111ff14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_details',
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=7), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_email'], ['customers.email'], ),
    sa.PrimaryKeyConstraint('customer_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_details')
    # ### end Alembic commands ###
