"""상품 테이블 - 재고 수량 컬럼 리팩토링(설정 수량, 구매한 수량, 조절 수량)

Revision ID: 19805a41764a
Revises: d06b19cb8302
Create Date: 2025-09-22 02:06:19.470286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19805a41764a'
down_revision: Union[str, Sequence[str], None] = 'd06b19cb8302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_product_info', sa.Column('purchased_quantity', sa.Integer(), nullable=False))
    op.add_column('store_product_info', sa.Column('admin_adjustment', sa.Integer(), nullable=False))
    op.drop_column('store_product_info', 'current_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_product_info', sa.Column('current_stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('store_product_info', 'admin_adjustment')
    op.drop_column('store_product_info', 'purchased_quantity')
    # ### end Alembic commands ###
