"""고객 즐겨찾기 테이블 추가

Revision ID: 31dfaee5fe42
Revises: 863c3695757f
Create Date: 2025-09-24 03:14:36.631584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31dfaee5fe42'
down_revision: Union[str, Sequence[str], None] = '863c3695757f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_favorites',
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_email'], ['customers.email'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('customer_email', 'store_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_favorites')
    # ### end Alembic commands ###
