"""가게, 상품, 결제 테이블 생성

Revision ID: 38d0b20148d7
Revises: 384be52479f3
Create Date: 2025-08-30 21:04:01.315063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d0b20148d7'
down_revision: Union[str, Sequence[str], None] = '384be52479f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('seller_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['seller_email'], ['sellers.email'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('store_payment_info',
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('portone_store_id', sa.String(length=255), nullable=True),
    sa.Column('portone_channel_id', sa.String(length=255), nullable=True),
    sa.Column('portone_secret_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('store_product_info',
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('initial_stock', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('sale', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('cart_items',
    sa.Column('payment_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['store_product_info.product_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('order_current_items',
    sa.Column('payment_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('reservation', 'complete', 'cancel', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['store_product_info.product_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('order_history_items',
    sa.Column('payment_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('reservation', 'complete', 'cancel', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['store_product_info.product_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_history_items')
    op.drop_table('order_current_items')
    op.drop_table('cart_items')
    op.drop_table('store_product_info')
    op.drop_table('store_payment_info')
    op.drop_table('stores')
    # ### end Alembic commands ###
