"""장바구니, 주문 테이블 - 최종 가격 컬럼 추가

Revision ID: 5bed9c3b3e8a
Revises: c4d2736ac7f7
Create Date: 2025-09-22 06:21:24.703730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bed9c3b3e8a'
down_revision: Union[str, Sequence[str], None] = 'c4d2736ac7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('total_amount', sa.Integer(), nullable=False))
    op.add_column('store_product_info', sa.Column('total_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_product_info', 'total_amount')
    op.drop_column('cart_items', 'total_amount')
    # ### end Alembic commands ###
