"""주문 테이블 - 픽업 준비 완료 컬럼 삭제

Revision ID: 5cdc727c6a30
Revises: e692df1f59d3
Create Date: 2025-09-18 01:23:56.217105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cdc727c6a30'
down_revision: Union[str, Sequence[str], None] = 'e692df1f59d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_current_items', 'pickup_ready_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_current_items', sa.Column('pickup_ready_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
