"""주문_상태_리팩토링_5단계_확장1

Revision ID: 6f53cccf8295
Revises: 38d0b20148d7
Create Date: 2025-09-04 05:15:38.616384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f53cccf8295'
down_revision: Union[str, Sequence[str], None] = '38d0b20148d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_current_items', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_current_items', sa.Column('pickup_ready_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_current_items', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('order_current_items', 'confirmed_at')
    op.add_column('order_history_items', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_history_items', sa.Column('pickup_ready_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_history_items', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('order_history_items', 'confirmed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history_items', sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('order_history_items', 'completed_at')
    op.drop_column('order_history_items', 'pickup_ready_at')
    op.drop_column('order_history_items', 'accepted_at')
    op.add_column('order_current_items', sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('order_current_items', 'completed_at')
    op.drop_column('order_current_items', 'pickup_ready_at')
    op.drop_column('order_current_items', 'accepted_at')
    # ### end Alembic commands ###
