"""판매자 가게 주소 & 상세 정보 컬럼 추가

Revision ID: 7c3f0f2ccb12
Revises: 09d0c4536d4a
Create Date: 2025-09-13 08:02:04.528786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3f0f2ccb12'
down_revision: Union[str, Sequence[str], None] = '09d0c4536d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sido', sa.String(length=50), nullable=False),
    sa.Column('sigungu', sa.String(length=50), nullable=False),
    sa.Column('bname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.add_column('stores', sa.Column('store_introduction', sa.Text(), nullable=True))
    op.add_column('stores', sa.Column('store_phone', sa.String(length=20), nullable=True))
    op.add_column('stores', sa.Column('store_postal_code', sa.String(length=10), nullable=True))
    op.add_column('stores', sa.Column('store_address', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('store_detail_address', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stores', 'addresses', ['address_id'], ['address_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'address_id')
    op.drop_column('stores', 'store_detail_address')
    op.drop_column('stores', 'store_address')
    op.drop_column('stores', 'store_postal_code')
    op.drop_column('stores', 'store_phone')
    op.drop_column('stores', 'store_introduction')
    op.drop_table('addresses')
    # ### end Alembic commands ###
