"""주문 테이블 - 최종 가격 저장에서 원가, 세일 정보 저장으로 변경 및 상품 정보 잘못 추가한 컬럼 삭제

Revision ID: 863c3695757f
Revises: 5bed9c3b3e8a
Create Date: 2025-09-22 06:45:55.936795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863c3695757f'
down_revision: Union[str, Sequence[str], None] = '5bed9c3b3e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_current_items', sa.Column('total_amount', sa.Integer(), nullable=False))
    op.drop_column('store_product_info', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_product_info', sa.Column('total_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('order_current_items', 'total_amount')
    # ### end Alembic commands ###
