"""소비자 영양 타입, 알레르기, 선호 메뉴 테이블 추가

Revision ID: 8a8f1111ff14
Revises: b4f2c8d9e3a1
Create Date: 2025-09-11 02:29:26.987010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8f1111ff14'
down_revision: Union[str, Sequence[str], None] = 'b4f2c8d9e3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_allergies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('allergy_type', sa.Enum('seafood', 'peanut', 'nuts', 'soy', 'wheat', 'egg', 'dairy', 'shellfish', 'fish', 'pork', 'beef', 'chicken', name='allergytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_email'], ['customers.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_nutrition_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('nutrition_type', sa.Enum('diet', 'LCHF', 'protein', 'LSLS', 'balance', 'vegetarian', name='nutritiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_email'], ['customers.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_preferred_menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('menu_type', sa.Enum('salad', 'poke', 'korean', 'sandwich', name='preferredmenu'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_email'], ['customers.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_preferred_menus')
    op.drop_table('customer_nutrition_types')
    op.drop_table('customer_allergies')
    # ### end Alembic commands ###
