"""가게 가까운 역 도보 시간 컬럼 추가

Revision ID: 947d2e807710
Revises: 74f193e5cbcd
Create Date: 2025-10-19 11:31:01.998227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '947d2e807710'
down_revision: Union[str, Sequence[str], None] = '74f193e5cbcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_addresses', sa.Column('nearest_station', sa.String(length=100), nullable=True))
    op.add_column('store_addresses', sa.Column('walking_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_addresses', 'walking_time')
    op.drop_column('store_addresses', 'nearest_station')
    # ### end Alembic commands ###
