"""주문 상태 수정: created_at -> reservation_at , canceled_at 컬럼 추가

Revision ID: a4456cc53bfb
Revises: 3423034ddc8b
Create Date: 2025-09-07 13:02:01.134181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4456cc53bfb'
down_revision: Union[str, Sequence[str], None] = '3423034ddc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_current_items', sa.Column('reservation_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('order_current_items', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('order_current_items', 'created_at')
    op.add_column('order_history_items', sa.Column('reservation_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('order_history_items', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('order_history_items', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('order_history_items', 'canceled_at')
    op.drop_column('order_history_items', 'reservation_at')
    op.add_column('order_current_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('order_current_items', 'canceled_at')
    op.drop_column('order_current_items', 'reservation_at')
    # ### end Alembic commands ###
