"""가게 위도, 경도 위치 정보 컬럼 추가

Revision ID: ab926b3beb8c
Revises: ac1decff424c
Create Date: 2025-09-15 07:40:51.866054

"""
from typing import Sequence, Union

from sqlalchemy.dialects.postgresql import ENUM
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab926b3beb8c'
down_revision: Union[str, Sequence[str], None] = 'ac1decff424c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Enum 객체를 미리 생성하고 create를 비활성화
    nutrition_type_enum = ENUM(
        'diet', 'LCHF', 'protein', 'LSLS', 'balance', 'vegetarian',
        name='nutritiontype',
        create_type=False
    )
    
    op.create_table('product_nutrition',
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('nutrition_type', nutrition_type_enum, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['store_product_info.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'nutrition_type')
    )
    op.add_column('addresses', sa.Column('lat', sa.String(length=50), nullable=False))
    op.add_column('addresses', sa.Column('lng', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'lng')
    op.drop_column('addresses', 'lat')
    op.drop_table('product_nutrition')
    # ### end Alembic commands ###
