"""소비자 토핑 정보 테이블 추가

Revision ID: ac1decff424c
Revises: f1408ccc3a63
Create Date: 2025-09-14 14:55:37.191030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1decff424c'
down_revision: Union[str, Sequence[str], None] = 'f1408ccc3a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_topping_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('topping_type', sa.Enum('egg_mayo', 'chicken_breast', 'onion_flake', 'toasted_bread', 'sweet_pumpkin', 'ricotta_cheese', 'shrimp', 'smoked_salmon', 'avocado', 'pork_belly', name='toppingtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_email'], ['customers.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_nutrition')
    op.drop_table('customer_topping_types')
    # ### end Alembic commands ###
