"""가게 운영 정보 & 운영 수정 예약 정보 테이블 추가

Revision ID: acede93e3279
Revises: ebad329de0a6
Create Date: 2025-09-13 15:40:10.577447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acede93e3279'
down_revision: Union[str, Sequence[str], None] = 'ebad329de0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_operation_info',
    sa.Column('operation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('pickup_start_time', sa.Time(), nullable=False),
    sa.Column('pickup_end_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('is_open_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_currently_open', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6'),
    sa.CheckConstraint('open_time < close_time'),
    sa.CheckConstraint('pickup_end_time > pickup_start_time AND pickup_end_time <= close_time'),
    sa.CheckConstraint('pickup_start_time >= open_time AND pickup_start_time < close_time'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('operation_id'),
    comment='가게 운영 정보 (요일별)'
    )
    op.create_table('store_operation_info_modifications',
    sa.Column('modification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('new_open_time', sa.Time(), nullable=True),
    sa.Column('new_pickup_start_time', sa.Time(), nullable=True),
    sa.Column('new_pickup_end_time', sa.Time(), nullable=True),
    sa.Column('new_close_time', sa.Time(), nullable=True),
    sa.Column('new_is_open_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('new_open_time < new_close_time', name='check_new_time_order'),
    sa.CheckConstraint('new_pickup_end_time > new_pickup_start_time AND new_pickup_end_time <= new_close_time', name='check_new_pickup_end'),
    sa.CheckConstraint('new_pickup_start_time >= new_open_time AND new_pickup_start_time < new_close_time', name='check_new_pickup_start'),
    sa.ForeignKeyConstraint(['operation_id'], ['store_operation_info.operation_id'], ),
    sa.PrimaryKeyConstraint('modification_id'),
    sa.UniqueConstraint('operation_id'),
    comment='가게 운영 정보 수정 예약'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_operation_info_modifications')
    op.drop_table('store_operation_info')
    # ### end Alembic commands ###
