"""장바구니, 주문 관련 테이블 컬럼 이름 수정 및 누락된 컬럼 추가

Revision ID: b96dec75bca7
Revises: 31dfaee5fe42
Create Date: 2025-09-24 07:22:13.007862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96dec75bca7'
down_revision: Union[str, Sequence[str], None] = '31dfaee5fe42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('customer_id', sa.String(length=255), nullable=False))
    op.drop_column('cart_items', 'user_id')
    op.add_column('order_current_items', sa.Column('customer_id', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'order_current_items', 'customers', ['customer_id'], ['email'])
    op.drop_column('order_current_items', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_current_items', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_current_items', type_='foreignkey')
    op.drop_column('order_current_items', 'customer_id')
    op.add_column('cart_items', sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('cart_items', 'customer_id')
    # ### end Alembic commands ###
