"""장바구니, 주문 테이블 - 최종 가격 저장에서 원가, 세일 정보 저장으로 변경

Revision ID: c4d2736ac7f7
Revises: 19805a41764a
Create Date: 2025-09-22 05:03:16.622789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d2736ac7f7'
down_revision: Union[str, Sequence[str], None] = '19805a41764a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('sale', sa.Integer(), nullable=True))
    op.add_column('order_current_items', sa.Column('sale', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_current_items', 'sale')
    op.drop_column('cart_items', 'sale')
    # ### end Alembic commands ###
