"""주문 테이블 - 취소 사유, 유저 선호 정보 컬럼 추가

Revision ID: d06b19cb8302
Revises: 5cdc727c6a30
Create Date: 2025-09-19 00:12:35.785407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06b19cb8302'
down_revision: Union[str, Sequence[str], None] = '5cdc727c6a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_current_items', sa.Column('cancel_reason', sa.String(length=500), nullable=True))
    op.add_column('order_current_items', sa.Column('preferred_menus', sa.String(length=500), nullable=True))
    op.add_column('order_current_items', sa.Column('nutrition_types', sa.String(length=500), nullable=True))
    op.add_column('order_current_items', sa.Column('allergies', sa.String(length=500), nullable=True))
    op.add_column('order_current_items', sa.Column('topping_types', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_current_items', 'topping_types')
    op.drop_column('order_current_items', 'allergies')
    op.drop_column('order_current_items', 'nutrition_types')
    op.drop_column('order_current_items', 'preferred_menus')
    op.drop_column('order_current_items', 'cancel_reason')
    # ### end Alembic commands ###
