"""가게 SNS & 이미지 테이블 추가

Revision ID: ebad329de0a6
Revises: 7c3f0f2ccb12
Create Date: 2025-09-13 13:29:35.858137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebad329de0a6'
down_revision: Union[str, Sequence[str], None] = '7c3f0f2ccb12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_images',
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('store_sns',
    sa.Column('sns_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('instagram', sa.Text(), nullable=True),
    sa.Column('facebook', sa.Text(), nullable=True),
    sa.Column('x', sa.Text(), nullable=True),
    sa.Column('homepage', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('sns_id'),
    sa.UniqueConstraint('store_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_sns')
    op.drop_table('store_images')
    # ### end Alembic commands ###
