"""상품 설명 컬럼 추가 & 상품 영양 정보 테이블 추가

Revision ID: f1408ccc3a63
Revises: acede93e3279
Create Date: 2025-09-13 16:11:16.650915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1408ccc3a63'
down_revision: Union[str, Sequence[str], None] = 'acede93e3279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_nutrition',
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('nutrition_type', sa.Enum('diet', 'LCHF', 'protein', 'LSLS', 'balance', 'vegetarian', name='nutritiontype'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['store_product_info.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'nutrition_type')
    )
    op.add_column('store_product_info', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_product_info', 'description')
    op.drop_table('product_nutrition')
    # ### end Alembic commands ###
