export const layoutMap = {
  default: {
    back: false,
    title: "",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  onBoarding: {
    back: true,
    title: "",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  Home: {
    back: false,
    title: "",
    centerIcon: true,
    loc: true,
    heart: true,
    noti: true,
  },
  SetLoc: {
    back: true,
    title: "위치 설정",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  Search: {
    back: true,
    title: "검색",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  FavStore: {
    back: true,
    title: "관심 가게",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  Noti: {
    back: true,
    title: "주문 알림",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  StoreDesc: {
    back: true,
    title: "매장 설명",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  Payment: {
    back: true,
    title: "결제",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  Order: {
    back: true,
    title: "주문 현황",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  OrderAll: {
    back: true,
    title: "주문 내역",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  My: {
    back: false,
    title: "마이페이지",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  ChangeInfo: {
    back: true,
    title: "프로필 수정",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  ChangeNutrition: {
    back: true,
    title: "영양 목표",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  ChangeAllergy: {
    back: true,
    title: "못먹는 음식",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  ChangeMenu: {
    back: true,
    title: "선호 메뉴",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
  ChangeTopping: {
    back: true,
    title: "선호 토핑",
    centerIcon: false,
    loc: false,
    heart: false,
    noti: false,
  },
};

export const sellerLayoutMap = {
  default: {
    back: false,
    title: "",
  },
  back: {
    back: true,
    title: "",
  },
  changeStoreInfo: {
    back: true,
    title: "매장 정보 변경",
  },
  changeOperationInfo: {
    back: true,
    title: "운영 정보 변경",
  },
  changePackageInfo: {
    back: true,
    title: "패키지 정보 변경",
  },
  billingHistory: {
    back: true,
    title: "정산 내역 확인",
  },
  billingChange: {
    back: true,
    title: "정산 정보 변경",
  },
};
