export const layoutMap = {
  default: {
    back: false,
    title: "",
    loc: false,
    heart: false,
    noti: false,
    search: false,
    searchPlaceholder: "",
  },
  onBoarding: {
    back: true,
    title: "",
    loc: false,
    heart: false,
    noti: false,
    search: false,
    searchPlaceholder: "",
  },
  Home: {
    back: false,
    title: "",
    loc: true,
    heart: true,
    noti: true,
    search: true,
    searchPlaceholder: "랜덤팩을 찾으시나요?",
  },
  SetLoc: {
    back: true,
    title: "위치 설정",
    loc: false,
    heart: false,
    noti: false,
    search: false,
    searchPlaceholder: "",
  },
  Search: {
    back: true,
    title: "검색",
    loc: false,
    heart: false,
    noti: false,
    search: true,
    searchPlaceholder: "가게명, 랜덤팩명을 검색하세요",
  },
  FavStore: {
    back: true,
    title: "관심 가게",
    loc: false,
    heart: false,
    noti: false,
    search: false,
    searchPlaceholder: "",
  },
  Noti: {
    back: true,
    title: "주문 알림",
    loc: false,
    heart: false,
    noti: false,
    search: false,
    searchPlaceholder: "",
  },
  StoreDesc: {
    back: true,
    title: "매장 설명",
    loc: false,
    heart: false,
    noti: false,
    search: false,
    searchPlaceholder: "",
  },
  Payment: {
    back: true,
    title: "결제",
    loc: false,
    heart: false,
    noti: false,
    search: false,
    searchPlaceholder: "",
  },
  Order: {
    back: false,
    title: "주문 현황",
    loc: false,
    heart: false,
    noti: true,
    search: false,
    searchPlaceholder: "",
  },
  My: {
    back: false,
    title: "마이페이지",
    loc: false,
    heart: false,
    noti: false,
    search: false,
    searchPlaceholder: "",
  },
};
